### ISSUE TITLE
Where is the implementations?

### ISSUE THREAD

**Issue by UdonDa** [xingchenzhang/MEFB#1]
Hi, Prof. Zhang.

I'm interested in this paper and I'd like to use this benchmark repository.

When will you share the codes?

Thank you.

**Comment by xingchenzhang** [comment]
Hi,

Thank you for your interest and sorry for the delay. I will release the codes recently.

**Comment by xingchenzhang** [comment]
> Hi, Prof. Zhang.
> 
> I'm interested in this paper and I'd like to use this benchmark repository.
> 
> When will you share the codes?
> 
> Thank you.

Hi,

Sorry for the delay, I have uploaded codes and given links to download fused images.

Regards,
Xingchen
