### ISSUE TITLE
I find the VIFB toolkit， and where is the MEFB‘s vision，it will open source？ thank u.

### ISSUE THREAD

**Issue by potoyeee** [xingchenzhang/MEFB#2]
I find the VIFB toolkit， and where is the MEFB‘s vision，it will open source？ thank u.

**Comment by xingchenzhang** [comment]
Yes, it will. I will release the code recently. Sorry for the delay!

**Comment by xingchenzhang** [comment]
> I find the VIFB toolkit， and where is the MEFB‘s vision，it will open source？ thank u.

Hi, 

Sorry for the delay. I have uploaded the codes and links to download fused images.

Thank you for your interest!

Regards,
Xingchen
