### ISSUE TITLE
Do these image pairs come with the GT image?

### ISSUE THREAD

**Issue by shinianzhihou** [xingchenzhang/MEFB#3]
THANKS

**Comment by xingchenzhang** [comment]
Hi,

There is no ground truth. Actually, image fusion tasks do not have real ground truth.

Bests,
Xingchen

**Comment by Guanys-dar** [comment]
But how the PSNR is calculated, if there is no ground truth?

**Comment by shinianzhihou** [comment]
NOT YET, MY BRO.

> But how the PSNR is calculated, if there is no ground truth?

**Comment by Guanys-dar** [comment]
Hahaha, I find the answer in one survey: "Deep Learning-based Multi-focus Image Fusion: A Survey and A Comparative Study". In section 4, the author describe how the PSNR, SSIM are calculated (use the fused image (output) and the source image (input) ). I was shocked when I learn about this in the paper.

在2023-03-21 21:32:18，Nian ***@***.***写道：

NOT YET, MY BRO.

But how the PSNR is calculated, if there is no ground truth?
